<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="LIN33002276"><DocLocation><![CDATA[C:\Framework\QTP-Hybrid-Framework\TestCases\orangehrm]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[orangehrm]]></DName>
<Res><![CDATA[Res8]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[[ username ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Admin"]]></Details>
<Time><![CDATA[14-02-2023 - 22:41:45]]></Time>
<TimeTick>1676394705</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" Source="Login" SourceLine="0" >
<Disp><![CDATA[[ username ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[[ password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63ebb9c063943e965fb990b91d7bd171871ad2e8e985"]]></Details>
<Time><![CDATA[14-02-2023 - 22:41:45]]></Time>
<TimeTick>1676394705</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="13" Source="Login" SourceLine="1" >
<Disp><![CDATA[[ password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[  Login  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:41:45]]></Time>
<TimeTick>1676394705</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="16" Source="Login" SourceLine="2" >
<Disp><![CDATA[[  Login  ].Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 22:41:45" eTime="14-02-2023 - 22:41:45" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[Login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T8">
<AName><![CDATA[Addemp]]></AName>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ PIM ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:41:47]]></Time>
<TimeTick>1676394707</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="21" Source="Addemp" SourceLine="0" >
<Disp><![CDATA[[ PIM ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[  Add  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:41:49]]></Time>
<TimeTick>1676394709</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="24" Source="Addemp" SourceLine="1" >
<Disp><![CDATA[[  Add  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ firstName ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Bangtan"]]></Details>
<Time><![CDATA[14-02-2023 - 22:41:51]]></Time>
<TimeTick>1676394711</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="29" Source="Addemp" SourceLine="2" >
<Disp><![CDATA[[ firstName ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ lastName ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Boys"]]></Details>
<Time><![CDATA[14-02-2023 - 22:41:51]]></Time>
<TimeTick>1676394711</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="32" Source="Addemp" SourceLine="3" >
<Disp><![CDATA[[ lastName ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7143"]]></Details>
<Time><![CDATA[14-02-2023 - 22:41:51]]></Time>
<TimeTick>1676394711</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="35" Source="Addemp" SourceLine="4" >
<Disp><![CDATA[[ WebEdit ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[  Save  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:41:51]]></Time>
<TimeTick>1676394711</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="38" Source="Addemp" SourceLine="5" >
<Disp><![CDATA[[  Save  ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ PIM ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:41:51]]></Time>
<TimeTick>1676394711</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="41" Source="Addemp" SourceLine="6" >
<Disp><![CDATA[[ PIM ].Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 22:41:45" eTime="14-02-2023 - 22:41:51" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="18" >
<Disp><![CDATA[Addemp Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T16">
<AName><![CDATA[Search]]></AName>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["02791"]]></Details>
<Time><![CDATA[14-02-2023 - 22:41:52]]></Time>
<TimeTick>1676394712</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="46" Source="Search" SourceLine="0" >
<Disp><![CDATA[[ WebEdit ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[  Search  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:41:52]]></Time>
<TimeTick>1676394712</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="49" Source="Search" SourceLine="1" >
<Disp><![CDATA[[  Search  ].Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 22:41:51" eTime="14-02-2023 - 22:41:52" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="43" >
<Disp><![CDATA[Search Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T19">
<AName><![CDATA[Delete]]></AName>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ WebCheckBox ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"[&nbsp;WebCheckBox&nbsp;]"&nbsp;(of&nbsp;class&nbsp;WebCheckBox).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[14-02-2023 - 22:42:13]]></Time>
<TimeTick>1676394733</TimeTick>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ WebCheckBox ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>xpath = //*[@id='app']/div[1]/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div/div/div[1]/div/div/label/span/i<br>Mercury Class = WebCheckBox<br>]]></Details>
<Time><![CDATA[14-02-2023 - 22:42:13]]></Time>
<TimeTick>1676394733</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="96" status="Warning" nType="Description" Source="Delete" SourceLine="0" >
<Disp><![CDATA[[ WebCheckBox ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="95" status="Failed" nType="Run Error" Source="Delete" SourceLine="0" >
<Disp><![CDATA[[ WebCheckBox ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;[ WebCheckBox ]&quot; (of class WebCheckBox).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (1): &quot;Browser(&quot;name:=OrangeHRM&quot;).Page(&quot;title:=OrangeHRM&quot;).WebCheckBox(&quot;xpath:=//*[@id='app']/div[1]/div[2]/div[2]/div/div[2]/div[3]/div/div[2]/div/div/div[1]/div/div/label/span/i&quot;).Set &quot;ON&quot;&quot;. ]]></Details>
<Time><![CDATA[14-02-2023 - 22:42:13]]></Time>
<TimeTick>1676394733</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="97" status="Failed" Source="Delete" SourceLine="0" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 22:41:52" eTime="14-02-2023 - 22:42:25" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="51" status="Failed" >
<Disp><![CDATA[Delete Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T23">
<AName><![CDATA[Logout]]></AName>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 22:42:25]]></Time>
<TimeTick>1676394745</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:42:25]]></Time>
<TimeTick>1676394745</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Seth Good.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:42:25]]></Time>
<TimeTick>1676394745</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="104" Source="Logout" SourceLine="0" >
<Disp><![CDATA[Seth Good.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[About Support Change Password.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Logout"]]></Details>
<Time><![CDATA[14-02-2023 - 22:42:25]]></Time>
<TimeTick>1676394745</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="107" Source="Logout" SourceLine="1" >
<Disp><![CDATA[About Support Change Password.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="11" nRep="103" Source="Logout" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="10" nRep="102" Source="Logout" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 22:42:25" eTime="14-02-2023 - 22:42:25" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="99" >
<Disp><![CDATA[Logout Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[orangehrm Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="14-02-2023 - 22:41:42" eTime="14-02-2023 - 22:42:25" passed="0" failed="2" warnings="1" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test orangehrm Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>