<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="LIN33002276"><DocLocation><![CDATA[C:\Framework\QTP-Hybrid-Framework\TestCases\orangehrm]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[orangehrm]]></DName>
<Res><![CDATA[Res3]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:25]]></Time>
<TimeTick>1676393545</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:25]]></Time>
<TimeTick>1676393545</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[username.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Admin"]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:25]]></Time>
<TimeTick>1676393545</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="12" Source="Login" SourceLine="0" >
<Disp><![CDATA[username.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63ebb9c063943e965fb990b91d7bd171871ad2e8e985"]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:25]]></Time>
<TimeTick>1676393545</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="15" Source="Login" SourceLine="1" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:25]]></Time>
<TimeTick>1676393545</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" Source="Login" SourceLine="2" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" Source="Login" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="10" Source="Login" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 22:22:24" eTime="14-02-2023 - 22:22:25" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[Login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T10">
<AName><![CDATA[Addemp]]></AName>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:26]]></Time>
<TimeTick>1676393546</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:26]]></Time>
<TimeTick>1676393546</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[PIM.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:26]]></Time>
<TimeTick>1676393546</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="25" Source="Addemp" SourceLine="0" >
<Disp><![CDATA[PIM.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="24" Source="Addemp" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:28]]></Time>
<TimeTick>1676393548</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Add.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:28]]></Time>
<TimeTick>1676393548</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="30" Source="Addemp" SourceLine="1" >
<Disp><![CDATA[Add.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="29" Source="Addemp" SourceLine="1" >
<Disp><![CDATA[OrangeHRM_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:30]]></Time>
<TimeTick>1676393550</TimeTick>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Bangtan"]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:30]]></Time>
<TimeTick>1676393550</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="34" Source="Addemp" SourceLine="2" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Boys"]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:30]]></Time>
<TimeTick>1676393550</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="37" Source="Addemp" SourceLine="3" >
<Disp><![CDATA[lastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[WebEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7143"]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:30]]></Time>
<TimeTick>1676393550</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="40" Source="Addemp" SourceLine="4" >
<Disp><![CDATA[WebEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:30]]></Time>
<TimeTick>1676393550</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="43" Source="Addemp" SourceLine="5" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="33" Source="Addemp" SourceLine="2" >
<Disp><![CDATA[OrangeHRM_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:30]]></Time>
<TimeTick>1676393550</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[PIM.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:30]]></Time>
<TimeTick>1676393550</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="47" Source="Addemp" SourceLine="6" >
<Disp><![CDATA[PIM.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="46" Source="Addemp" SourceLine="6" >
<Disp><![CDATA[OrangeHRM_4]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="23" Source="Addemp" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 22:22:25" eTime="14-02-2023 - 22:22:30" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="20" >
<Disp><![CDATA[Addemp Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T23">
<AName><![CDATA[Search]]></AName>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:31]]></Time>
<TimeTick>1676393551</TimeTick>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:31]]></Time>
<TimeTick>1676393551</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[WebEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["02791"]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:31]]></Time>
<TimeTick>1676393551</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="54" Source="Search" SourceLine="0" >
<Disp><![CDATA[WebEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:31]]></Time>
<TimeTick>1676393551</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="57" Source="Search" SourceLine="1" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="53" Source="Search" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="52" Source="Search" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 22:22:30" eTime="14-02-2023 - 22:22:31" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="49" >
<Disp><![CDATA[Search Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T28">
<AName><![CDATA[Delete]]></AName>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:32]]></Time>
<TimeTick>1676393552</TimeTick>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:32]]></Time>
<TimeTick>1676393552</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA["WebCheckBox_2"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (51 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>type=checkbox<br>role=<br>name=<br>micclass=WebCheckBox<br>html tag=INPUT<br>acc_name=<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (51 objects found)&nbsp;</FONT></u><br>
micclass=WebCheckBox<br>html tag=INPUT<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=<SPAN class=passed> (Used</SPAN>, 51 matches)</SPAN><br>type=checkbox<SPAN class=passed> (Used</SPAN>, 51 matches)</SPAN><br>html id=<SPAN class=passed> (Used</SPAN>, 51 matches)</SPAN><br>value=0<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>class=<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>visible=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:32]]></Time>
<TimeTick>1676393552</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="65" Source="Delete" SourceLine="0" >
<Disp><![CDATA["WebCheckBox_2"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[WebCheckBox_2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:32]]></Time>
<TimeTick>1676393552</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="66" Source="Delete" SourceLine="0" >
<Disp><![CDATA[WebCheckBox_2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Delete Selected]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Delete&nbsp;Selected"&nbsp;(of&nbsp;class&nbsp;WebButton).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:53]]></Time>
<TimeTick>1676393573</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Delete Selected]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebButton<br>Html Tag = BUTTON<br>_xpath = //DIV/DIV/DIV/BUTTON[normalize-space()="Delete Selected"]<br>|Visible = -1<br>Value = Delete Selected<br>Type = button<br>Name = Delete Selected<br>Html Id = <br>DHTML Class = oxd-button oxd-button--medium oxd-button--label-danger orangehrm-horizontal-margin<br>acc_name = <br>]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:53]]></Time>
<TimeTick>1676393573</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="111" status="Warning" nType="Description" Source="Delete" SourceLine="1" >
<Disp><![CDATA[Delete Selected]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="110" status="Failed" nType="Run Error" Source="Delete" SourceLine="1" >
<Disp><![CDATA[Delete Selected]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="64" status="Failed" Source="Delete" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="63" status="Failed" Source="Delete" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:53]]></Time>
<TimeTick>1676393573</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Delete Selected&quot; (of class WebButton).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (2): &quot;Browser(&quot;OrangeHRM&quot;).Page(&quot;OrangeHRM&quot;).WebButton(&quot;Delete Selected&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[14-02-2023 - 22:22:53]]></Time>
<TimeTick>1676393573</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="113" status="Failed" Source="Delete" SourceLine="1" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:23:23]]></Time>
<TimeTick>1676393603</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Yes, Delete]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot&nbsp;identify&nbsp;the&nbsp;object&nbsp;"Yes,&nbsp;Delete"&nbsp;(of&nbsp;class&nbsp;WebButton).<br/>Verify&nbsp;that&nbsp;this&nbsp;object's&nbsp;properties&nbsp;match&nbsp;an&nbsp;object&nbsp;currently&nbsp;displayed&nbsp;in&nbsp;your&nbsp;application.]]></Details>
<Time><![CDATA[14-02-2023 - 22:23:23]]></Time>
<TimeTick>1676393603</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Yes, Delete]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Mercury Class = WebButton<br>Html Tag = BUTTON<br>_xpath = //DIV/BUTTON[normalize-space()="Yes, Delete"]<br>|Visible = -1<br>Value = Yes, Delete<br>Type = button<br>Name = Yes, Delete<br>Html Id = <br>DHTML Class = oxd-button oxd-button--medium oxd-button--label-danger orangehrm-button-margin<br>acc_name = <br>]]></Details>
<Time><![CDATA[14-02-2023 - 22:23:23]]></Time>
<TimeTick>1676393603</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="159" status="Warning" nType="Description" Source="Delete" SourceLine="1" >
<Disp><![CDATA[Yes, Delete]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="8" nRep="158" status="Failed" nType="Run Error" Source="Delete" SourceLine="1" >
<Disp><![CDATA[Yes, Delete]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="157" status="Failed" Source="Delete" SourceLine="1" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="112" status="Failed" Source="Delete" SourceLine="1" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 22:23:23]]></Time>
<TimeTick>1676393603</TimeTick>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot identify the object &quot;Yes, Delete&quot; (of class WebButton).<BR/>Verify that this object's properties match an object currently displayed in your application.<BR/>Line (3): &quot;Browser(&quot;OrangeHRM&quot;).Page(&quot;OrangeHRM&quot;).WebButton(&quot;Yes, Delete&quot;).Click&quot;. ]]></Details>
<Time><![CDATA[14-02-2023 - 22:23:23]]></Time>
<TimeTick>1676393603</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="161" status="Failed" Source="Delete" SourceLine="2" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="160" status="Failed" Source="Delete" SourceLine="2" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 22:22:31" eTime="14-02-2023 - 22:23:24" passed="0" failed="4" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="59" status="Failed" >
<Disp><![CDATA[Delete Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T42">
<AName><![CDATA[Logout]]></AName>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 22:23:25]]></Time>
<TimeTick>1676393605</TimeTick>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:23:25]]></Time>
<TimeTick>1676393605</TimeTick>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[Seth Good.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:23:25]]></Time>
<TimeTick>1676393605</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="168" Source="Logout" SourceLine="0" >
<Disp><![CDATA[Seth Good.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[About Support Change Password.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Logout"]]></Details>
<Time><![CDATA[14-02-2023 - 22:23:25]]></Time>
<TimeTick>1676393605</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="171" Source="Logout" SourceLine="1" >
<Disp><![CDATA[About Support Change Password.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="167" Source="Logout" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="166" Source="Logout" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 22:23:24" eTime="14-02-2023 - 22:23:25" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="163" >
<Disp><![CDATA[Logout Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[orangehrm Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="14-02-2023 - 22:22:21" eTime="14-02-2023 - 22:23:25" passed="0" failed="4" warnings="2" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test orangehrm Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>