<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="LIN33002276"><DocLocation><![CDATA[C:\Framework\QTP-Hybrid-Framework\TestCases\orangehrm]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[orangehrm]]></DName>
<Res><![CDATA[Res5]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Login]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[[ username ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Admin"]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:40]]></Time>
<TimeTick>1676393920</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="10" Source="Login" SourceLine="0" >
<Disp><![CDATA[[ username ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[[ password ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["63ebb9c063943e965fb990b91d7bd171871ad2e8e985"]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:40]]></Time>
<TimeTick>1676393920</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="13" Source="Login" SourceLine="1" >
<Disp><![CDATA[[ password ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[  Login  ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:40]]></Time>
<TimeTick>1676393920</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="16" Source="Login" SourceLine="2" >
<Disp><![CDATA[[  Login  ].Click]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 22:28:40" eTime="14-02-2023 - 22:28:40" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" >
<Disp><![CDATA[Login Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T8">
<AName><![CDATA[Addemp]]></AName>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:42]]></Time>
<TimeTick>1676393922</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:42]]></Time>
<TimeTick>1676393922</TimeTick>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[PIM.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:42]]></Time>
<TimeTick>1676393922</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="23" Source="Addemp" SourceLine="0" >
<Disp><![CDATA[PIM.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="22" Source="Addemp" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:44]]></Time>
<TimeTick>1676393924</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Add.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:44]]></Time>
<TimeTick>1676393924</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" Source="Addemp" SourceLine="1" >
<Disp><![CDATA[Add.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="26" Source="Addemp" SourceLine="1" >
<Disp><![CDATA[OrangeHRM_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:45]]></Time>
<TimeTick>1676393925</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[firstName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Bangtan"]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:45]]></Time>
<TimeTick>1676393925</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="31" Source="Addemp" SourceLine="2" >
<Disp><![CDATA[firstName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[lastName.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Boys"]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:45]]></Time>
<TimeTick>1676393925</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="34" Source="Addemp" SourceLine="3" >
<Disp><![CDATA[lastName.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[WebEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["7143"]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:45]]></Time>
<TimeTick>1676393925</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="37" Source="Addemp" SourceLine="4" >
<Disp><![CDATA[WebEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:45]]></Time>
<TimeTick>1676393925</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="40" Source="Addemp" SourceLine="5" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="30" Source="Addemp" SourceLine="2" >
<Disp><![CDATA[OrangeHRM_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[OrangeHRM_4]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:45]]></Time>
<TimeTick>1676393925</TimeTick>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[PIM.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:45]]></Time>
<TimeTick>1676393925</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="44" Source="Addemp" SourceLine="6" >
<Disp><![CDATA[PIM.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="43" Source="Addemp" SourceLine="6" >
<Disp><![CDATA[OrangeHRM_4]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="21" Source="Addemp" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 22:28:41" eTime="14-02-2023 - 22:28:45" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="18" >
<Disp><![CDATA[Addemp Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T21">
<AName><![CDATA[Search]]></AName>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:47]]></Time>
<TimeTick>1676393927</TimeTick>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:47]]></Time>
<TimeTick>1676393927</TimeTick>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[WebEdit.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["02791"]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:47]]></Time>
<TimeTick>1676393927</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="52" Source="Search" SourceLine="0" >
<Disp><![CDATA[WebEdit.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[Search.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:47]]></Time>
<TimeTick>1676393927</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="55" Source="Search" SourceLine="1" >
<Disp><![CDATA[Search.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="51" Source="Search" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="50" Source="Search" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 22:28:46" eTime="14-02-2023 - 22:28:47" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="46" >
<Disp><![CDATA[Search Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T26">
<AName><![CDATA[Delete]]></AName>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:48]]></Time>
<TimeTick>1676393928</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:48]]></Time>
<TimeTick>1676393928</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[WebCheckBox_2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:48]]></Time>
<TimeTick>1676393928</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="63" Source="Delete" SourceLine="0" >
<Disp><![CDATA[WebCheckBox_2.Set]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="62" Source="Delete" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="61" Source="Delete" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 22:28:47" eTime="14-02-2023 - 22:28:48" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="57" >
<Disp><![CDATA[Delete Summary]]></Disp>
</NodeArgs>
</Action>
<Action rID="T30">
<AName><![CDATA[Logout]]></AName>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:48]]></Time>
<TimeTick>1676393928</TimeTick>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[OrangeHRM]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:48]]></Time>
<TimeTick>1676393928</TimeTick>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Seth Good.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:48]]></Time>
<TimeTick>1676393928</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="70" Source="Logout" SourceLine="0" >
<Disp><![CDATA[Seth Good.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[About Support Change Password.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Logout"]]></Details>
<Time><![CDATA[14-02-2023 - 22:28:48]]></Time>
<TimeTick>1676393928</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="73" Source="Logout" SourceLine="1" >
<Disp><![CDATA[About Support Change Password.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="69" Source="Logout" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="68" Source="Logout" SourceLine="0" >
<Disp><![CDATA[OrangeHRM]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="14-02-2023 - 22:28:48" eTime="14-02-2023 - 22:28:48" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="65" >
<Disp><![CDATA[Logout Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" >
<Disp><![CDATA[orangehrm Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="14-02-2023 - 22:28:37" eTime="14-02-2023 - 22:28:48" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test orangehrm Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>